version: '3'
services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      - docker
    links:
      - docker
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_docker_certs:/certs/client:ro
      - ${HOME}/.aws:/var/jenkins_home/.aws:ro
    networks:
      - jenkins
    env_file:
      - .env

  docker:
    container_name: jenkins_docker
    image: docker:dind
    privileged: true
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    ports:
      - 2376:2376
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_docker_certs:/certs/client
    command: --storage-driver=overlay2

networks:
  jenkins:

volumes:
  jenkins_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./jenkins_data
  jenkins_docker_certs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./jenkins_certs